// Generated by npm run images:generate
import infinityPool320 from '../assets/photos/infinity-pool-320.webp'
import infinityPool640 from '../assets/photos/infinity-pool-640.webp'
import infinityPool960 from '../assets/photos/infinity-pool-960.webp'
import infinityPool1024 from '../assets/photos/infinity-pool-1024.webp'
import hotelLobby320 from '../assets/photos/hotel-lobby-320.webp'
import hotelLobby640 from '../assets/photos/hotel-lobby-640.webp'
import hotelLobby960 from '../assets/photos/hotel-lobby-960.webp'
import hotelLobby1024 from '../assets/photos/hotel-lobby-1024.webp'
import trifwaysLakesideHotel320 from '../assets/photos/trifways-lakeside-hotel-320.webp'
import trifwaysLakesideHotel640 from '../assets/photos/trifways-lakeside-hotel-640.webp'
import trifwaysLakesideHotel960 from '../assets/photos/trifways-lakeside-hotel-960.webp'
import trifwaysLakesideHotel1440 from '../assets/photos/trifways-lakeside-hotel-1440.webp'
import trifwaysLakesideHotel1672 from '../assets/photos/trifways-lakeside-hotel-1672.webp'
import mountainLodge320 from '../assets/photos/mountain-lodge-320.webp'
import mountainLodge640 from '../assets/photos/mountain-lodge-640.webp'
import mountainLodge960 from '../assets/photos/mountain-lodge-960.webp'
import mountainLodge1200 from '../assets/photos/mountain-lodge-1200.webp'
import rusticSuite320 from '../assets/photos/rustic-suite-320.webp'
import rusticSuite640 from '../assets/photos/rustic-suite-640.webp'
import rusticSuite960 from '../assets/photos/rustic-suite-960.webp'
import rusticSuite1200 from '../assets/photos/rustic-suite-1200.webp'
import adventureLodge320 from '../assets/photos/adventure-lodge-320.webp'
import adventureLodge640 from '../assets/photos/adventure-lodge-640.webp'
import adventureLodge960 from '../assets/photos/adventure-lodge-960.webp'
import adventureLodge1200 from '../assets/photos/adventure-lodge-1200.webp'

export const staticPhotos = {
  infinityPool: {
    src: infinityPool1024,
    srcSet: `${infinityPool320} 320w, ${infinityPool640} 640w, ${infinityPool960} 960w, ${infinityPool1024} 1024w`,
  },
  hotelLobby: {
    src: hotelLobby1024,
    srcSet: `${hotelLobby320} 320w, ${hotelLobby640} 640w, ${hotelLobby960} 960w, ${hotelLobby1024} 1024w`,
  },
  trifwaysLakesideHotel: {
    src: trifwaysLakesideHotel1672,
    srcSet: `${trifwaysLakesideHotel320} 320w, ${trifwaysLakesideHotel640} 640w, ${trifwaysLakesideHotel960} 960w, ${trifwaysLakesideHotel1440} 1440w, ${trifwaysLakesideHotel1672} 1672w`,
  },
  mountainLodge: {
    src: mountainLodge1200,
    srcSet: `${mountainLodge320} 320w, ${mountainLodge640} 640w, ${mountainLodge960} 960w, ${mountainLodge1200} 1200w`,
  },
  rusticSuite: {
    src: rusticSuite1200,
    srcSet: `${rusticSuite320} 320w, ${rusticSuite640} 640w, ${rusticSuite960} 960w, ${rusticSuite1200} 1200w`,
  },
  adventureLodge: {
    src: adventureLodge1200,
    srcSet: `${adventureLodge320} 320w, ${adventureLodge640} 640w, ${adventureLodge960} 960w, ${adventureLodge1200} 1200w`,
  },
} as const
