/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SelectLocationRouteImport } from './routes/select-location'
import { Route as PostLoginRouteImport } from './routes/post-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AdminWalkInIndexRouteImport } from './routes/admin/walk-in/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminRoomsIndexRouteImport } from './routes/admin/rooms/index'
import { Route as AdminHotelsIndexRouteImport } from './routes/admin/hotels/index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings/index'
import { Route as AdminHotelsHotelIdRouteImport } from './routes/admin/hotels/$hotelId'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin/bookings/$bookingId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectLocationRoute = SelectLocationRouteImport.update({
  id: '/select-location',
  path: '/select-location',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLoginRoute = PostLoginRouteImport.update({
  id: '/post-login',
  path: '/post-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminWalkInIndexRoute = AdminWalkInIndexRouteImport.update({
  id: '/walk-in/',
  path: '/walk-in/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsIndexRoute = AdminRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsIndexRoute = AdminHotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsHotelIdRoute = AdminHotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/post-login': typeof PostLoginRoute
  '/select-location': typeof SelectLocationRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/bookings': typeof AuthenticatedBookingsRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/hotels/': typeof AdminHotelsIndexRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/walk-in/': typeof AdminWalkInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post-login': typeof PostLoginRoute
  '/select-location': typeof SelectLocationRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/bookings': typeof AuthenticatedBookingsRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/hotels': typeof AdminHotelsIndexRoute
  '/admin/rooms': typeof AdminRoomsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/walk-in': typeof AdminWalkInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/post-login': typeof PostLoginRoute
  '/select-location': typeof SelectLocationRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/hotels/': typeof AdminHotelsIndexRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/walk-in/': typeof AdminWalkInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/post-login'
    | '/select-location'
    | '/sign-in'
    | '/sign-up'
    | '/bookings'
    | '/hotels/$hotelId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/admin/bookings/$bookingId'
    | '/admin/hotels/$hotelId'
    | '/admin/bookings/'
    | '/admin/hotels/'
    | '/admin/rooms/'
    | '/admin/users/'
    | '/admin/walk-in/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/post-login'
    | '/select-location'
    | '/sign-in'
    | '/sign-up'
    | '/bookings'
    | '/hotels/$hotelId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/admin/bookings/$bookingId'
    | '/admin/hotels/$hotelId'
    | '/admin/bookings'
    | '/admin/hotels'
    | '/admin/rooms'
    | '/admin/users'
    | '/admin/walk-in'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/post-login'
    | '/select-location'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/bookings'
    | '/hotels/$hotelId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/admin/bookings/$bookingId'
    | '/admin/hotels/$hotelId'
    | '/admin/bookings/'
    | '/admin/hotels/'
    | '/admin/rooms/'
    | '/admin/users/'
    | '/admin/walk-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  PostLoginRoute: typeof PostLoginRoute
  SelectLocationRoute: typeof SelectLocationRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-location': {
      id: '/select-location'
      path: '/select-location'
      fullPath: '/select-location'
      preLoaderRoute: typeof SelectLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-login': {
      id: '/post-login'
      path: '/post-login'
      fullPath: '/post-login'
      preLoaderRoute: typeof PostLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/walk-in/': {
      id: '/admin/walk-in/'
      path: '/walk-in'
      fullPath: '/admin/walk-in/'
      preLoaderRoute: typeof AdminWalkInIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms/': {
      id: '/admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AdminRoomsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels/': {
      id: '/admin/hotels/'
      path: '/hotels'
      fullPath: '/admin/hotels/'
      preLoaderRoute: typeof AdminHotelsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels/$hotelId': {
      id: '/admin/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/admin/hotels/$hotelId'
      preLoaderRoute: typeof AdminHotelsHotelIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
  AdminHotelsHotelIdRoute: typeof AdminHotelsHotelIdRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminHotelsIndexRoute: typeof AdminHotelsIndexRoute
  AdminRoomsIndexRoute: typeof AdminRoomsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWalkInIndexRoute: typeof AdminWalkInIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
  AdminHotelsHotelIdRoute: AdminHotelsHotelIdRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminHotelsIndexRoute: AdminHotelsIndexRoute,
  AdminRoomsIndexRoute: AdminRoomsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWalkInIndexRoute: AdminWalkInIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  PostLoginRoute: PostLoginRoute,
  SelectLocationRoute: SelectLocationRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
